# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-01 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('gmt_modify', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('modifier', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=20)),
                ('commit', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
